<?php
namespace backend\models;

use common\models\Blog;
use backend\models\ALTBlogTag;
use backend\models\ALTTag;
use yii\db\Query;

class ALTBlog extends Blog
{
    public function afterSave($insert, $changedAttributes)
    {

        if (!empty($this->tags)) {
            //Get old tags to remove unused (deleted)
            $oldTags = (new Query())
                ->from('blog_tag')
                ->where(['blog_id' => $this->id])
                ->indexBy('tag_id')
                ->all();

            foreach ($this->tags as $tag) {
                $findTag = (new Query())
                    ->from('tag')
                    ->where(['name' => $tag])
                    ->indexBy('name')
                    ->one();

                //Add new tag if it doesn't exist
                if (empty($findTag)) {
                    //Add new tag
                    $newTag = new ALTTag();
                    $newTag->name = $tag;
                    $newTag->priority = 1000;
                    $newTag->save();
                    //Add tag to blog post (blog_tag)
                    $addBlogTagRelation = new ALTBlogTag();
                    $addBlogTagRelation->blog_id = $this->id;
                    $addBlogTagRelation->tag_id = $newTag->id;
                    $addBlogTagRelation->save();
                } else {
                    //Check if tag exists in a blog post
                    if (isset($oldTags[$findTag['id']])) {
                        //Remove from the list of tags for deletion
                        unset($oldTags[$findTag['id']]);
                    } else {
                        //Add tag to blog post (blog_tag)
                        $addBlogTagRelation = new ALTBlogTag();
                        $addBlogTagRelation->blog_id = $this->id;
                        $addBlogTagRelation->tag_id = $findTag['id'];
                        $addBlogTagRelation->save();
                    }
                }
            }
        } else {
            //Delete all tags if tags field is empty
            ALTBlogTag::deleteAll(['blog_id' => $this->id]);
        }

        if (!empty($oldTags)) {
            //Delete tags that are missing from the tags field (deleted tags)
            ALTBlogTag::deleteAll(['AND',
                ['blog_id' => $this->id],
                ['IN', 'tag_id', array_keys($oldTags)]]);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}